Traceback (most recent call last):
  File "C:\my_projects\comadoro\src\gui.py", line 90, in OnButtonClicked
    raise(ValueError('testing...'))
ValueError: testing...
Traceback (most recent call last):
  File "C:\my_projects\comadoro\src\gui.py", line 90, in OnButtonClicked
    raise(ValueError('testing...'))
ValueError: testing...
Traceback (most recent call last):
  File "C:\my_projects\comadoro\src\gui.py", line 90, in OnButtonClicked
    raise(ValueError('testing...'))
ValueError: testing...
Traceback (most recent call last):
  File "C:\my_projects\comadoro\src\gui.py", line 91, in OnButtonClicked
    raise(ValueError('testing...'))
ValueError: testing...
Exception in thread Thread-1 (run_timer):
Traceback (most recent call last):
  File "C:\python_file\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\python_file\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\my_projects\comadoro\src\gui.py", line 111, in run_timer
    raise(ValueError('testing...'))
ValueError: testing...
Exception in thread Thread-1 (run_timer):
Traceback (most recent call last):
  File "C:\python_file\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\python_file\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\my_projects\comadoro\src\gui.py", line 111, in run_timer
    raise(ValueError('testing...'))
ValueError: testing...
Exception in thread Thread-2 (run_timer):
Traceback (most recent call last):
  File "C:\python_file\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\python_file\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\my_projects\comadoro\src\gui.py", line 111, in run_timer
    raise(ValueError('testing...'))
ValueError: testing...
Exception in thread Thread-1 (run_timer):
Traceback (most recent call last):
  File "C:\python_file\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\python_file\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\my_projects\comadoro\src\gui.py", line 111, in run_timer
    raise(ValueError('testing...'))
ValueError: testing...
